### ISSUE TITLE
How to perform tree pattern matching?

### ISSUE THREAD

**Issue by khawarizmus** [mike-lischke/antlr4ng#12]
I was looking at the available documentation offered by Antlr and came across [Tree pattern matching](https://github.com/antlr/antlr4/blob/master/doc/tree-matching.md#parse-tree-patterns) which I find useful.

However, after trying to replicate the example I couldn't figure out how to do it. and the method `compileParseTreePattern` doesn't seem to be implemented in this package.

Can you provide us with a minimal example? assuming that is possible with the current version

**Comment by mike-lischke** [comment]
This is a part which has not been implemented.
