### ISSUE TITLE
Generated parser doesn't export `start` or `query` method to get the tree.

### ISSUE THREAD

**Issue by nikolalukovic** [mike-lischke/antlr4ng#24]
Pretty much whats in the title.
I wanted to generate the parser/lexer and visitor for this language: 
- https://github.com/antlr/grammars-v4/tree/master/kuka

And used this cli command to generate the code (as was shown in the README):
```
antlr4ng -Dlanguage=TypeScript -visitor -listener src/grammar/krl/krl.g4
```
Also a potentionally stupid question but the grammar and lexer/parser clearly specify the loops and for loop, but I don't see it in the visitor as an option to visit? Is that a bug or is there another way to do that?

**Comment by mike-lischke** [comment]
It doesn't export neither `start` nor `query` because this grammar doesn't contain any rule with one of these names. The top level rule seems to be [module](https://github.com/antlr/grammars-v4/blob/master/kuka/krl.g4#L26).

**Comment by nikolalukovic** [comment]
Well that's it. I'm stupid. Thanks for the help and sorry for spam.
