### ISSUE TITLE
getRuleContext is incompatible with generated code (2.0.5)

### ISSUE THREAD

**Issue by EliotVU** [mike-lischke/antlr4ng#26]
As seen in this screenshot:
![image](https://github.com/mike-lischke/antlr4ng/assets/808593/7c40dee0-bdbe-42e6-a713-c4eb4e4ac907)

The generated code is incompatible with the declared method "getRuleContext", e.g. `Argument of type 'typeof IdentifierContext' is not assignable to parameter of type 'new (...args: unknown[]) => IdentifierContext'.ts(2345)
`

**Comment by mike-lischke** [comment]
Odd, that was changed [in this commit](https://github.com/mike-lischke/antlr4ng/commit/ce232f8732c91056152fadfba29d1352a6cc97f3), to allow any constructor. And this changed has been published in 2.0.5.

And looking at the bundle I see that code there. Are you sure you have 2.0.5 in your project?

**Comment by EliotVU** [comment]
That was my thought at first too, I have confirmed the code is that of 2.0.5, also you can tell by the screenshot's error popup it lists the new type as seen in your commit. :/

**Comment by mike-lischke** [comment]
Can you post your `IdentifierContext` class here? Is there something unusual in its constructor?

Try also changing the typings file to use `...args?: unknown[]` instead.

**Comment by mike-lischke** [comment]
Meanwhile I saw this in one of my projects too and tbh. I'm totally perplexed. The behavior is different depending on the project, even though the context signatures are the same. All deps are at their latest version (particularly TypeScript) and I don't understand why one project works and the other does not.

**Comment by Console-buche** [comment]
Hi there,
Quick note to let you know we've also had this issue and patched it to `any` temporarily.

**Comment by mike-lischke** [comment]
This is fixed in 2.0.10
