### ISSUE TITLE
ReferenceError: Super constructor may only be called once

### ISSUE THREAD

**Issue by DuShuYuan** [mike-lischke/antlr4ng#30]
"antlr4": "4.13.1",
    "antlr4-c3": "3.3.5",
    "antlr4ng": "2.0.10",

The location of the error：
![1706758290883](https://github.com/mike-lischke/antlr4ng/assets/11830896/bc555c6c-c5d8-4a2a-8497-98c0a90b0d27)

I guess the corresponding code position should be：
![image](https://github.com/mike-lischke/antlr4ng/assets/11830896/c22fea96-ae5e-45b8-b69b-08130238c539)

I see a similar code in antlr4-c3 as well.

It's mine tsconfig.json:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "incremental": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2015",
    "module": "ESNext",
    "lib": [
      "DOM",
      "ESNext"
    ]
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }
}

```

tsconfig.worker.json:
```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/worker",
    "lib": [
      "ES2021",
      "webworker"
    ],
    "types": ["node"]
  },
  "include": [
    "src/**/*.worker.ts"
  ]
}

```

I think it can be solved this way：
```
class Parent {
  constructor(arg = null) {
    // ...
  }
}

class Child extends Parent {
  constructor(e) {
    super(e || someDefaultValue); // e is used if it exists, otherwise the default value is used
  }
}

```

**Comment by mike-lischke** [comment]
This is a bogus error. The super constructor is in fact only called once. Sometimes you cannot easily define parameters to inherited methods using the nullish coalescing operator or similar constructs, particularly in method overload situations.

**Comment by DuShuYuan** [comment]
> This is a bogus error. The super constructor is in fact only called once. Sometimes you cannot easily define parameters to inherited methods using the nullish coalescing operator or similar constructs, particularly in method overload situations.

Please how can I fix this error, my project is not running now

**Comment by mike-lischke** [comment]
I can try to debug that if you give me an example (as a repo or full code here), which reproduces the issue. As I wrote above, IMO it's not an error.

**Comment by DuShuYuan** [comment]
Thanks, I've solved it, I modified the constructor.
But I don't understand why a different constructor is called depending on the argument, why not just call super(...).

![image](https://github.com/mike-lischke/antlr4ng/assets/11830896/a00ca407-4844-4506-a911-caba2e16f22b)
![image](https://github.com/mike-lischke/antlr4ng/assets/11830896/a8d74736-66d0-4365-ada4-ee0aa15f5d63)

**Comment by mike-lischke** [comment]
Strange that this is accepted by your tsc. It should not! Keep in mind this is a method overloading situation. The two overloads either allow no parameters at all or exactly two. If you use `invokingStateNumber` directly you violate this requirement, because this parameter can be unassigned, leading to the situation that only one parameter is given.

Are you directly transpiling with `tsc`? Do you have an automatic syntax checker in your project (like VS Code has)?

**Comment by DuShuYuan** [comment]
Cause:
Modify "target": "ES2021" in tsconfig.json

![image](https://github.com/mike-lischke/antlr4ng/assets/11830896/200742e8-f8b1-4e40-807a-29bf1d278a4d)

**Comment by mike-lischke** [comment]
You can always bundle your code to support older ES versions. The bundler will then generate wrappers or polyfills from unsupported code.

**Comment by nashbridges** [comment]
I think we see the same error. The weird thing, it happens only in a production build, where the code is transpiled by Webpack.

Here's the excerpt of the transpiled code (which it seems corresponds to [`InterpreterRuleContext`](https://github.com/mike-lischke/antlr4ng/blob/fbda0196b2db6a767367e3deafb7d2b8e80f3e86/src/InterpreterRuleContext.ts#L21-L38):

```js
function PV(e, t) {
  if (t.has(e)) throw new TypeError("Cannot initialize the same private elements twice on an object")
}

function IV(e, t, n) {
  PV(e, t), t.set(e, n)
}

function LV(e, t, n) {
  return function(e, t, n) {
    if (t.set) t.set.call(e, n);
    else {
      if (!t.writable) throw new TypeError("attempted to set read only private field");
      t.value = n
    }
  }

  Xre = (Iee = new WeakMap, class extends jte {
    constructor(e, t, n) {
      void 0 !== n ? (super(t, n), IV(this, Iee, {
        writable: !0,
        value: void 0
      })) : (super(), super(t, n), IV(this, Iee, {
        writable: !0,
        value: void 0
      })), LV(this, Iee, e)
    }
    get ruleIndex() {
      return kV(this, Iee)
    }
  })
```

Notice the `super(), super(t, n)`

We use the ESM version of the library, which is distributed as 

```js
var Pt = class extends q {
  #e;
  constructor(e, t, r) {
    r !== void 0 ? super(t, r) : super(), this.#e = e
  }
  get ruleIndex() {
    return this.#e
  }
}
```

**Comment by mike-lischke** [comment]
Oh, so it's a webpack problem actually? Thanks for the analysis @nashbridges. I guess I need to find a different way then to implement this.

**Comment by nashbridges** [comment]
Right. Sorry for being confusing. This is either webpack or, more likely, babel's plugin issue. I haven't yet checked if upgrading them would help. 
Another potential fix is to bump up browserlist, so that private properties would not have to be transpiled, but that's not an option for many.

**Comment by nashbridges** [comment]
> Another potential fix is to bump up browserlist

I can confirm that setting "last 2 years" in the browserlist makes the issue disappear.

**Comment by mike-lischke** [comment]
@nashbridges I'd like to use the suggested values from the [NPM docs](https://www.npmjs.com/package/browserslist). Would that also work?

**Comment by nashbridges** [comment]
Yes, setting "defaults and fully supports es6-module" also helps with the issue.
