### ISSUE TITLE
Where does the code for antlr4-4.13.2-SNAPSHOT-complete.jar come from?

### ISSUE THREAD

**Issue by nchen63** [mike-lischke/antlr4ng#36]
Is it the same as the JAR file built from https://github.com/antlr/antlr4 or is there an ng version stored somewhere?

**Comment by mike-lischke** [comment]
Yes, the jar has been generated using standard ANTLR4. The only difference to the official jar is that it uses different group templates for TypeScript, which allows to generate parser files compatible with antlr4ng. This is btw. the same approach that antlr4ts uses.

**Comment by mike-lischke** [comment]
No. This is the one from antlr4ts. I have an own [group template](https://github.com/mike-lischke/antlr4/blob/dev/tool/resources/org/antlr/v4/tool/templates/codegen/TypeScript/TypeScript.stg).

**Comment by nchen63** [comment]
It would be a lot easier to find and to keep in sync if it was in the same repo as antlr4ng

**Comment by mike-lischke** [comment]
That's the ultimate plan for ANLTRng. Once ANTLR4 has been ported to TS and new runtime concept will be inplemented where everything related to a runtime (its template files, tests, builds and releases) are done by the runtime author and no longer by the tool author.
