### ISSUE TITLE
[bug]: antlr4ng-cli generates parser with type errors

### ISSUE THREAD

**Issue by HaydenOrz** [mike-lischke/antlr4ng#37]
First of all, thank you for your excellent work. Both antlr4ng and antlr4-c3 are great.

## Description
I'm trying to migrate from antlr4ts to antlr4ng. https://github.com/DTStack/dt-sql-parser/pull/261 
Then I had some problems. The parser I generated directly via `antlr4ng-cli` comes with some type errors.

<img width="931" alt="image" src="https://github.com/mike-lischke/antlr4ng/assets/58289241/aedb07f4-2aed-42d5-b6d9-544b232fae35">

<img width="1440" alt="image" src="https://github.com/mike-lischke/antlr4ng/assets/58289241/8e8c9aa0-7eb1-4316-bf64-1d907556fd5b">

Looks like the `antlr.` is missing in front of the `ParserRuleContext`.

Maybe it's because I'm having a problem with my grammar file, but I need help.

## Minimal demo to reproducing the problem

https://github.com/HaydenOrz/antlr4ng-trino

**Comment by mike-lischke** [comment]
I see, that's a special case where a parameter is passed around. Thanks for that clean minimal demo!

**Comment by mike-lischke** [comment]
I believe this is not a bug actually. Parameters can be anything, including primitive types, so the generator cannot simply assume it's always a runtime type like a `ParserRuleContext`. Instead you should make this explicit by:

```
predicate[antlr.ParserRuleContext value]
    : comparisonOperator right= valueExpression                                     # comparison
    | comparisonOperator comparisonQuantifier '(' query ')'                         # quantifiedComparison
    | KW_NOT? KW_BETWEEN lower= valueExpression KW_AND upper= valueExpression       # between
    | KW_NOT? KW_IN '(' expression (',' expression)* ')'                            # inList
    | KW_NOT? KW_IN '(' query ')'                                                   # inSubquery
    | KW_NOT? KW_LIKE pattern= valueExpression (KW_ESCAPE escape= valueExpression)? # like
    | KW_IS KW_NOT? KW_NULL                                                         # nullPredicate
    | KW_IS KW_NOT? KW_DISTINCT KW_FROM right= valueExpression                      # distinctFrom
    ;
```

**Comment by HaydenOrz** [comment]
I see, I need to modify the grammar files to fit antlr4ng. 

Thanks, the problem has been solved.
