### ISSUE TITLE
Exception in production mode of webpack

### ISSUE THREAD

**Issue by HaydenOrz** [mike-lischke/antlr4ng#38]
## Description
In Webpack's production mode, if the `optimization.minimize` option is turned on (Webpack has this option turned on by default), will get an error.

![image](https://github.com/mike-lischke/antlr4ng/assets/58289241/bd46930f-276b-45e7-9bea-69d917e23e44)

![image](https://github.com/mike-lischke/antlr4ng/assets/58289241/d6c56a93-cbe2-43cf-9d4d-d71f06b465c1)

It looks like it might be an issue with the compression tool, but I feel the need to report this issue to you, because webpack is very widely used.

## Minimal demo to reproducing the problem
https://github.com/HaydenOrz/antlr4ng-trino

<br/>

The good news is that Antlr4ng performs well in all of these situations:
+ NodeJS
+ Vite
+ Webpack development mode
+ webpack production mode and turn the `optimization.minimize` option off

**Comment by mike-lischke** [comment]
Usually, the error that a type is not defined when running a TS/JS app, means that it wasn't imported yet (because of circular dependencies). However, when bundled, such an error should never come up, since everything is in one file. Unless of course, you have separated certain parts into own bundles. I do that with vite using the rollup option `manualChunks` and have seen this error in certain situations.

**Comment by HaydenOrz** [comment]
> I do that with vite using the [rollup option manualChunks](https://github.com/mysql/mysql-shell-plugins/blob/master/gui/frontend/vite.config.ts#L166) and have seen this error in certain situations.

I made a similar attempt, but I didn't find this issue in the vite project. This issue doesn't seem to be related to chunk distribution. Currently I'm only reproducing this issue in production mode for webpack.  And when I turned off webpack's [optimization.minimize](https://webpack.js.org/configuration/optimization/#optimizationminimize) option, this issue no longer appears. In addition, when Webpack builds an application, code compression occurs after chunk distribution.

So for now, I'm simply thinking that the issue is only due to webpack's built-in code compression plugin. With this as a premise, I made some attempts.  I noticed that antlr4ng uses esbuild to build the release package, and the minify option is turned on at build time.  And by default, webpack uses the [TerserWebpackPlugin](https://webpack.js.org/plugins/terser-webpack-plugin/) to compress the code.  And it supports the use of [esbuild](https://webpack.js.org/plugins/terser-webpack-plugin/#esbuild) for compression.

Then, Then, I did the following in the [demo](https://github.com/HaydenOrz/antlr4ng-trino) mentioned above:

Installed dependencies
```shell
npm install esbuild terser-webpack-plugin -D
```

Modified `webpack.prod.config.js`
```javascript
const devConfig = require('./webpack.config');
const TerserPlugin = require('terser-webpack-plugin');

delete devConfig.devServer;
delete devConfig.devtool;

// devConfig.devtool = 'source-map'

devConfig.mode = 'production';
devConfig.optimization = {
	minimizer: [
		new TerserPlugin({
			minify: TerserPlugin.esbuildMinify,
		}),
	],
};

module.exports = devConfig;
```

Then the problem no longer appears.

**Comment by HaydenOrz** [comment]
I'm not familiar with code compression, but it looks like it's the result of a conflict between code compression plugins.

Also, I think antlr4ng might fix this by not turning on the minify option at build time. This requires some additional testing.

**Comment by HaydenOrz** [comment]
I did some trying, turned off minify for antlr4ng, and tested it in the webpack project, and the results were frustrating.

### The process is as follows：
Run following commands in antlr4ng:

```shell 
npm run build

npm run pack
```

Then I got a tarball of antlr4ng, named `antlr4ng-2.0.10.tgz`.

Move it to the root directory of the demo project above and run the following command in the demo project：
```shell
npm install ./antlr4ng-2.0.10.tgz
```

Then I build the demo project and preview it, but I still get the following error：

![image](https://github.com/mike-lischke/antlr4ng/assets/58289241/85fecfca-f634-4b20-b1f4-15aa6a2f4c10)

**Comment by HaydenOrz** [comment]
I made another attempt to abandon esbuild to bundle when antlr4ng build, and only compile with tsc.
Then I found that antlr4ng built like this worked well in the webpack project without any issues.

I believe the problem may be with webpack or terser, but at the moment I haven't found a good way to get antlr4ng to work with webpack and terser.

If you have any progress on this issue, please let me know, appreciated.

**Comment by mike-lischke** [comment]
Hey @HaydenOrz, thanks for the PR. Hopefully this has no impact on the execution speed.

**Comment by mike-lischke** [comment]
If it's urgent I can try to set out new releases today.

**Comment by HaydenOrz** [comment]
> If it's urgent I can try to set out new releases today.

That couldn't be better

I need to finish switching at runtime within this week.

Also, I created the [same PR ](https://github.com/mike-lischke/antlr4-c3/pull/97) in antlr4-c3 and solved the same issue.  I hope that antlr4-c3 can be upgraded to a new version of antlr4ng and that antlr4-c3 will also be released.

**Comment by smoelker** [comment]
For those who still face this issue and find themselves here looking for a solution: I got the same `_ParseTreeWalker is not defined` error on production builds but NOT on development builds. Turns out the root case was a difference in `browserslist` settings for development and production. After updating the `browserslist` settings to a sensible value, all worked fine again.
