### ISSUE TITLE
About BigInt's browser compatibility

### ISSUE THREAD

**Issue by HaydenOrz** [mike-lischke/antlr4ng#39]
I noticed that antlr4ng uses BigInts. BigInts require ES2020. 

BigInts are not lowered to older syntax in esbuild  https://github.com/evanw/esbuild/issues/732 . If I set esbuild's target option to be lower than es2020, then esbuild throws an exception about not being able to convert bigint.  Babel also has[ a similar issue ](https://babeljs.io/docs/babel-plugin-syntax-bigint).

Whether to consider replacing Bigint and BigUint64Array with number and Uint16Array. 

This has the potential to affect the performance of antlr4ng, and in general the long type in java should indeed correspond to the javascript Bigint and BigUint64Array (since both are 64-bit). But there is currently no good solution to the compatibility problem.

**Comment by mike-lischke** [comment]
Yes, that's true. In fact I don't write any TS code that requires ES erlier than 2022 (though 2020 would probably work too). All relevant browsers and Node.js support that. We should not support old technology forever in new code.

**Comment by HaydenOrz** [comment]
I can create a new PR to change it if you need to.

**Comment by mike-lischke** [comment]
Sure, why not! PR is welcome.

**Comment by mike-lischke** [comment]
PR is merged
