### ISSUE TITLE
ParserRulecontext.parent() incorrectly typed

### ISSUE THREAD

**Issue by jlchmura** [mike-lischke/antlr4ng#46]
In version 3, `parent()` is now typed as `this` (https://github.com/mike-lischke/antlr4ng/blob/3afee898cdb33ddac439a8d1ae78443c11eed62e/src/ParserRuleContext.ts#L231C26-L231C30), which I believe is incorrect. It should be set to `ParserRuleContext`. 

When inherited by a specific parser context class in a generated parser, this results in the parent having the same type as the context itself.

E.g.
```
visitFooExpression = (ctx: FooExpressionContext) {
  const fooParent = ctx.parent(); // this will now be of type FooExpressionContext, but should it? 
}
```

The side-effect to this is that to cast the parent context you now have to use `unknown`
```
visitFooExpression = (ctx: FooExpressionContext) {
  const fooParent = ctx.parent() as unknown as SomeParentExpressionContext; 
}
```

**Comment by mike-lischke** [comment]
This was changed mainly to avoid having to cast parent access to `ParserRuleContext` in generated parsers. Originally this was implemented in `RuleContext`, so this was a good workaround. But now that I removed `RuleContext` the type of the parent can indeed be set to `ParserRuleContext`.
