### ISSUE TITLE
ATNConfig.reachesIntoOuterContext should be an "int" (number)

### ISSUE THREAD

**Issue by kaby76** [mike-lischke/antlr4ng#49]
Going through the parser trace diffs. 

ATNConfig.reachesIntoOuterContext should be an "int" (number), as it is defined in [CSharp](https://github.com/antlr/antlr4/blob/69cfd8e49b911c4a0483035b100fd438f1a55841/runtime/CSharp/src/Atn/ATNConfig.cs#L67), [Java](https://github.com/antlr/antlr4/blob/69cfd8e49b911c4a0483035b100fd438f1a55841/runtime/Java/src/org/antlr/v4/runtime/atn/ATNConfig.java#L65), assigned as a number in [JavaScript](https://github.com/antlr/antlr4/blob/69cfd8e49b911c4a0483035b100fd438f1a55841/runtime/JavaScript/src/antlr4/atn/ATNConfig.js#L13), but defined as a boolean in [Antlr4ng](https://github.com/mike-lischke/antlr4ng/blob/8d0aceff0dcedf9f97880f57e3fae535dc889365/src/atn/ATNConfig.ts#L33). We can confirm that with a call to int Max(a,b) called in [CSharp](https://github.com/antlr/antlr4/blob/69cfd8e49b911c4a0483035b100fd438f1a55841/runtime/CSharp/src/Atn/ATNConfigSet.cs#L119), [Java](https://github.com/antlr/antlr4/blob/69cfd8e49b911c4a0483035b100fd438f1a55841/runtime/Java/src/org/antlr/v4/runtime/atn/ATNConfigSet.java#L159), [JavaScript](https://github.com/antlr/antlr4/blob/69cfd8e49b911c4a0483035b100fd438f1a55841/runtime/JavaScript/src/antlr4/atn/ATNConfigSet.js#L118), but not [Antlr4ng](https://github.com/mike-lischke/antlr4ng/blob/8d0aceff0dcedf9f97880f57e3fae535dc889365/src/atn/ATNConfigSet.ts#L164).

**Comment by mike-lischke** [comment]
Yes, I know, but a comment in the source code says it can be a boolean, because it is never decremented (so it's always yes or no).
