### ISSUE TITLE
Fails with Safari < 16.6

### ISSUE THREAD

**Issue by Raubzeug** [mike-lischke/antlr4ng#65]
I try to use your package, but my build fails in Safari < 16.6. The problem is here https://caniuse.com/?search=static%20initialization .
It seems that this bug will go away if you use in your `tsconfig.json`  `"target": "ES5"`, but it's some unsupported constructions in your code base (`#foo` in general).

Could you please help me to handle with it?

**Comment by mike-lischke** [comment]
I have no intention to make the package work with older target versions. But you are open to take the sources, switch to something that works for you (e.g. ES5) and let a bundler (e.g. esbuild) convert the code that can be executed in, say, Safari < 16.6.
