### ISSUE TITLE
BufferedTokenStream getHiddenTokensToLeft and getHiddenTokensToRight types declarations missing

### ISSUE THREAD

**Issue by br0nstein** [mike-lischke/antlr4ng#7]
Instead BufferedTokenStream.d.ts declares functions `hiddenTokensToLeft` and `hiddenTokensToRight` which do not exist

**Comment by br0nstein** [comment]
Also, for compatibility with antlr4ts, I would suggest returning an empty array when it would return no hidden tokens. Currently it returns null.

**Comment by mike-lischke** [comment]
I'm leaning towards how it is done in Java, in cases where antlr4ts differs. This is a progress and might end up in a way we don't know yet. But for getting the initial conversion ready that's the goal I'm following.

**Comment by br0nstein** [comment]
Thanks Mike. Although it’s a work in progress, I managed to port my project from antlr4ts to antlr4ng and can confirm your implementation appears to be bug-free with my grammar, at least as far as my test coverage goes. Big kudos for that. There were some differences in the debugging experience—I’d give the edge to antlr4ts at least for my workflow of exploring the ParseTree, so I’d recommend exploring that when you have a chance.

That said, I think I’ll unfortunately need to stay with antlr4ts for the foreseeable future due to its performance being about 2x as fast on some complex queries parsed with my grammar (due to the optimizations made in the antlr4 fork by tunnelvisionlabs that it’s based on). That project appears unmaintained. If you’re looking for more work.. :)

**Comment by mike-lischke** [comment]
I made quite a different experience. I [measured the speed of different runtimes](https://github.com/mike-lischke/antlr4wasm/blob/master/benchmarks/mysql/readme.md) with my (really big ) MySQL grammar and found antlr4ts being the slowest or second slowest, which made me pick the JS target to work further on, instead of antlr4ts.
