### ISSUE TITLE
[TS Error]ParserRuleContext‘s children has error type

### ISSUE THREAD

**Issue by Cythia828** [mike-lischke/antlr4ng#79]
<img width="758" alt="image" src="https://github.com/mike-lischke/antlr4ng/assets/21350892/63ee478a-721f-4a66-9ad3-822bfcfdd23c">
<img width="773" alt="image" src="https://github.com/mike-lischke/antlr4ng/assets/21350892/549fb86d-2431-4b2a-bcce-1972fa4b093a">

Hello~
There is a TS problem.
When somewhere is using `ParserRuleContext`'s `children`,we can find the child's type is error.Because every item's type of children is `ParseTree`. 
TS Error: Type 'ParseTree' cannot be assigned to type 'ParserRuleContextWithAttr'.
The type "ParseTree" is missing the following properties of the type "ParserRuleContext": start, stop, exception, copyFrom, and 20 other items.

**Comment by mike-lischke** [comment]
Have you tried to use a cast from your `ParseTree` instances to the `ParserRuleContextWithAttr` type?

**Comment by Cythia828** [comment]
The transform between `ParserRuleContext` and `ParserRuleContextWithAttr `'s type has been done.
Actually, it's a problem between `ParseTree` and `ParserRuleContext`.
In my opinion, as `ParserRuleContext`'s `children`, its item should be `ParserRuleContext` type, too.But it's `ParseTree` in fact.
<img width="724" alt="image" src="https://github.com/mike-lischke/antlr4ng/assets/21350892/6a253bba-0d88-4024-a9ef-c29c21f1cdd9">

TS Error: The type "ParseTree" is missing the following properties of the type "ParserRuleContext": start, stop, exception, copyFrom, and 20 other items. ts(2740).

**Comment by Cythia828** [comment]
You make a good point. I'll give your suggestion some serious thought.
