### ISSUE TITLE
Wrong property name

### ISSUE THREAD

**Issue by EtienneDuv** [mike-lischke/antlr4ng#8]
**Problem:**  Parser's getter `syntaxErrorsCount` at `src/Parser.js:302` is inconsistent with type `src/Parser.d.ts:53`  `syntaxErrorCount`. 
This results in typescript not building unless adding `@ts-ignore` + autocomplete is wrong

**Solution:** Change either of them, but I would change the `syntaxErrorsCount` to `syntaxErrorCount` to be consistent with `antlr4ts`

Thanks for your work :)

**Comment by mike-lischke** [comment]
oh, good find! This should be a no-brainer, once everything is in TypeScript.

**Comment by EtienneDuv** [comment]
When can I expect the fix ? Just to know, as I wanted to use the lib for work

**Comment by mike-lischke** [comment]
Hmm, I'm thinking of a new release next weekend, as I have a couple changes in the generator too.

**Comment by mike-lischke** [comment]
Fixed in 1.1.7
