### ISSUE TITLE
Error TS2380 in CommonToken.d.ts

### ISSUE THREAD

**Issue by abelykh0** [mike-lischke/antlr4ng#98]
Getting this error when building:
error: [1] /node_modules/antlr4ng/dist/CommonToken.d.ts(86,9): error TS2380: The return type of a 'get' accessor must be assignable to its 'set' accessor type
https://github.com/mike-lischke/antlr4ng/blob/main/src/CommonToken.ts#L194
https://github.com/mike-lischke/antlr4ng/blob/main/src/CommonToken.ts#L212

**Comment by mike-lischke** [comment]
TS version?

**Comment by abelykh0** [comment]
> TS version?

I assume 4.6.2.

This is what I am getting from build (build is complex and involves a lot of other things):
[0] ts-loader: Using ttypescript@4.6.2. This version may or may not be compatible with ts-loader.

**Comment by mike-lischke** [comment]
Please upgrade to 5.1 or newer (this condition has been relaxed in [this PR]( https://github.com/microsoft/TypeScript/pull/53417).
