### ISSUE TITLE
Error TS2304 in ParseTreePatternMatcher.d.ts

### ISSUE THREAD

**Issue by abelykh0** [mike-lischke/antlr4ng#99]
Getting error while building
error: [1] /node_modules/antlr4ng/dist/tree/pattern/ParseTreePatternMatcher.d.ts(87,54): error TS2304: Cannot find name 'ErrorOptions'.

Sorry, no idea where it comes from, there's no ErrorOptions in ParseTreePatternMatcher.ts

**Comment by mike-lischke** [comment]
Could be due to TS configuration. `ErrorOptions` comes from JS `Error`.
